### ISSUE TITLE
Passing tests without using given args

### ISSUE THREAD

**Issue by sheenasany** [learn-co-curriculum/python-p3-translating-from-orms-to-sqlalchemy-lab#9]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/209225?module_item_id=482537

### Concern

Couple of things here that could be confusing for students: 

- I'm able to pass the final test without having to use the `dog` argument. 
- The `new_from_db` function starter code only has one argument of `session` being passed in, but on initial run of the tests, it says that it expects 2 args, but only received one. Should the starter code for this function also include the second argument like the other functions in this lab? I could see how this could be confusing for students if they were coming in thinking that most of the arguments are made for them.
- Should there be any mention that they would need to import Dog from models? Maybe including a hint or a reminder that they would need to do so could help with this. 

Just some thoughts.

**Comment by professor-ben** [comment]
Looking into this now.
